


export const SET_USER = 'SET_USER';
export const SPECIAL_MESSAGE_SHOW = 'SPECIAL_MESSAGE_SHOW';
export const RESOURCE_LIMIT_SHOW = 'RESOURCE_LIMIT_SHOW';

//ECOMMERCE
export const PURCHASE_CREATE = 'PURCHASE_CREATE';
export const PURCHASE_CREATE_SUCCESS = 'PURCHASE_CREATE_SUCCESS';

// export const PURCHASE_DELETE = 'PURCHASE_DELETE';
// export const PURCHASE_DELETE_SUCCESS = 'PURCHASE_DELETE_SUCCESS';

export const PURCHASE_UPDATE = 'PURCHASE_UPDATE';
export const PURCHASE_UPDATE_SUCCESS = 'PURCHASE_UPDATE_SUCCESS';